sudo: required
services:
  - docker

before_install:
  - docker build -t emrmarvin/react-test -f ./client/Dockerfile.dev ./client

secript:
  - docker run emrmarvin/react-test npm test -- --coverage

after_success:
  - docker build -t emrmarvin/multi-client ./client
  - docker build -t emrmarvin/multi-nginx ./nginx
  - docker build -t emrmarvin/multi-server ./server
  - docker build -t emrmarvin/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images to docker hub
  - docker push emrmarvin/multi-client
  - docker push emrmarvin/multi-nginx
  - docker push emrmarvin/multi-server
  - docker push emrmarvin/multi-worker
